function solutions_trsoftware_commons_TestCommons_JUnit(){var O='bootstrap',P='begin',Q='gwt.codesvr.solutions.trsoftware.commons.TestCommons.JUnit=',R='gwt.codesvr=',S='solutions.trsoftware.commons.TestCommons.JUnit',T='startup',U='DUMMY',V=0,W=1,X='iframe',Y='position:absolute; width:0; height:0; border:none; left: -1000px;',Z=' top: -1000px;',$='CSS1Compat',_='<!doctype html>',ab='',bb='<html><head><\/head><body><\/body><\/html>',cb='undefined',db='readystatechange',eb=10,fb='Chrome',gb='eval("',hb='");',ib='script',jb='javascript',kb='moduleStartup',lb='moduleRequested',mb='solutions_trsoftware_commons_TestCommons_JUnit',nb='Failed to load ',ob='head',pb='meta',qb='name',rb='solutions.trsoftware.commons.TestCommons.JUnit::',sb='::',tb='gwt:property',ub='content',vb='=',wb='gwt:onPropertyErrorFn',xb='Bad handler "',yb='" for "gwt:onPropertyErrorFn"',zb='gwt:onLoadErrorFn',Ab='" for "gwt:onLoadErrorFn"',Bb='#',Cb='?',Db='/',Eb='img',Fb='clear.cache.gif',Gb='baseUrl',Hb='solutions.trsoftware.commons.TestCommons.JUnit.nocache.js',Ib='base',Jb='//',Kb='chromeWithColNumbers',Lb='\n',Mb='runStyleHtmlUnit',Nb='selectingPermutation',Ob='solutions.trsoftware.commons.TestCommons.JUnit.devmode.js',Pb='false',Qb='C05E049EEAE22C890F9F0EC6E8B006FC',Rb='true',Sb='C25A1304ECE38B2D7FE01C93C9505713',Tb=':',Ub='.cache.js',Vb='loadExternalRefs',Wb='end',Xb='http:',Yb='file:',Zb='_gwt_dummy_',$b='__gwtDevModeHook:solutions.trsoftware.commons.TestCommons.JUnit',_b='Ignoring non-whitelisted Dev Mode URL: ',ac=':moduleBase';var o=window;var p=document;r(O,P);function q(){var a=o.location.search;return a.indexOf(Q)!=-1||a.indexOf(R)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:S,sessionId:o.__gwtStatsSessionId,subSystem:T,evtGroup:a,millis:(new Date).getTime(),type:b})}}
solutions_trsoftware_commons_TestCommons_JUnit.__sendStats=r;solutions_trsoftware_commons_TestCommons_JUnit.__moduleName=S;solutions_trsoftware_commons_TestCommons_JUnit.__errFn=null;solutions_trsoftware_commons_TestCommons_JUnit.__moduleBase=U;solutions_trsoftware_commons_TestCommons_JUnit.__softPermutationId=V;solutions_trsoftware_commons_TestCommons_JUnit.__computePropValue=null;solutions_trsoftware_commons_TestCommons_JUnit.__getPropMap=null;solutions_trsoftware_commons_TestCommons_JUnit.__installRunAsyncCode=function(){};solutions_trsoftware_commons_TestCommons_JUnit.__gwtStartLoadingFragment=function(){return null};solutions_trsoftware_commons_TestCommons_JUnit.__gwt_isKnownPropertyValue=function(){return false};solutions_trsoftware_commons_TestCommons_JUnit.__gwt_getMetaProperty=function(){return null};var s=null;var t=o.__gwt_activeModules=o.__gwt_activeModules||{};t[S]={moduleName:S};solutions_trsoftware_commons_TestCommons_JUnit.__moduleStartupDone=function(e){var f=t[S].bindings;t[S].bindings=function(){var a=f?f():{};var b=e[solutions_trsoftware_commons_TestCommons_JUnit.__softPermutationId];for(var c=V;c<b.length;c++){var d=b[c];a[d[V]]=d[W]}return a}};var u;function v(){w();return u}
function w(){if(u){return}var a=p.createElement(X);a.id=S;a.style.cssText=Y+Z;a.tabIndex=-1;p.body.appendChild(a);u=a.contentWindow.document;u.open();var b=document.compatMode==$?_:ab;u.write(b+bb);u.close()}
function A(k){function l(a){function b(){if(typeof p.readyState==cb){return typeof p.body!=cb&&p.body!=null}return /loaded|complete/.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){if(!b()){return}c=true;a();if(p.removeEventListener){p.removeEventListener(db,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener(db,d,false)}var e=setInterval(function(){d()},eb)}
function m(c){function d(a,b){a.removeChild(b)}
var e=v();var f=e.body;var g;if(navigator.userAgent.indexOf(fb)>-1&&window.JSON){var h=e.createDocumentFragment();h.appendChild(e.createTextNode(gb));for(var i=V;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(e.createTextNode(j.substring(W,j.length-W)))}h.appendChild(e.createTextNode(hb));g=e.createElement(ib);g.language=jb;g.appendChild(h);f.appendChild(g);d(f,g)}else{for(var i=V;i<c.length;i++){g=e.createElement(ib);g.language=jb;g.text=c[i];f.appendChild(g);d(f,g)}}}
solutions_trsoftware_commons_TestCommons_JUnit.onScriptDownloaded=function(a){l(function(){m(a)})};r(kb,lb);var n=p.createElement(ib);n.src=k;if(solutions_trsoftware_commons_TestCommons_JUnit.__errFn){n.onerror=function(){solutions_trsoftware_commons_TestCommons_JUnit.__errFn(mb,new Error(nb+code))}}p.getElementsByTagName(ob)[V].appendChild(n)}
solutions_trsoftware_commons_TestCommons_JUnit.__startLoadingFragment=function(a){return D(a)};solutions_trsoftware_commons_TestCommons_JUnit.__installRunAsyncCode=function(a){var b=v();var c=b.body;var d=b.createElement(ib);d.language=jb;d.text=a;c.appendChild(d);c.removeChild(d)};function B(){var c={};var d;var e;var f=p.getElementsByTagName(pb);for(var g=V,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(qb),k;if(j){j=j.replace(rb,ab);if(j.indexOf(sb)>=V){continue}if(j==tb){k=i.getAttribute(ub);if(k){var l,m=k.indexOf(vb);if(m>=V){j=k.substring(V,m);l=k.substring(m+W)}else{j=k;l=ab}c[j]=l}}else if(j==wb){k=i.getAttribute(ub);if(k){try{d=eval(k)}catch(a){alert(xb+k+yb)}}}else if(j==zb){k=i.getAttribute(ub);if(k){try{e=eval(k)}catch(a){alert(xb+k+Ab)}}}}}__gwt_getMetaProperty=function(a){var b=c[a];return b==null?null:b};s=d;solutions_trsoftware_commons_TestCommons_JUnit.__errFn=e}
function C(){function e(a){var b=a.lastIndexOf(Bb);if(b==-1){b=a.length}var c=a.indexOf(Cb);if(c==-1){c=a.length}var d=a.lastIndexOf(Db,Math.min(c,b));return d>=V?a.substring(V,d+W):ab}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=p.createElement(Eb);b.src=a+Fb;a=e(b.src)}return a}
function g(){var a=__gwt_getMetaProperty(Gb);if(a!=null){return a}return ab}
function h(){var a=p.getElementsByTagName(ib);for(var b=V;b<a.length;++b){if(a[b].src.indexOf(Hb)!=-1){return e(a[b].src)}}return ab}
function i(){var a=p.getElementsByTagName(Ib);if(a.length>V){return a[a.length-W].href}return ab}
function j(){var a=p.location;return a.href==a.protocol+Jb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==ab){k=h()}if(k==ab){k=i()}if(k==ab&&j()){k=e(p.location.href)}k=f(k);return k}
function D(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return solutions_trsoftware_commons_TestCommons_JUnit.__moduleBase+a}
function F(){var f=[];var g=V;function h(a,b){var c=f;for(var d=V,e=a.length-W;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var i=[];var j=[];function k(a){var b=j[a](),c=i[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(s){s(a,d,b)}throw null}
j[Kb]=function(){if(Error&&Error.captureStackTrace){try{null.a()}catch(a){if(a.stack){var b=a.stack.split(Lb);if(b&&(b.length>W&&/:\d+:\d+\)?\s*$/.test(b[W]))){return true}}}}return false};i[Kb]={'false':V,'true':W};j[Mb]=function(){return __gwt_getMetaProperty(Mb)};i[Mb]={'false':V,'true':W};__gwt_isKnownPropertyValue=function(a,b){return b in i[a]};solutions_trsoftware_commons_TestCommons_JUnit.__getPropMap=function(){var a={};for(var b in i){if(i.hasOwnProperty(b)){a[b]=k(b)}}return a};solutions_trsoftware_commons_TestCommons_JUnit.__computePropValue=k;o.__gwt_activeModules[S].bindings=solutions_trsoftware_commons_TestCommons_JUnit.__getPropMap;r(O,Nb);if(q()){return D(Ob)}var l;try{h([Pb,Pb],Qb);h([Pb,Rb],Sb);l=f[k(Kb)][k(Mb)];var m=l.indexOf(Tb);if(m!=-1){g=parseInt(l.substring(m+W),eb);l=l.substring(V,m)}}catch(a){}solutions_trsoftware_commons_TestCommons_JUnit.__softPermutationId=g;return D(l+Ub)}
function G(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}r(Vb,P);r(Vb,Wb)}
B();solutions_trsoftware_commons_TestCommons_JUnit.__moduleBase=C();t[S].moduleBase=solutions_trsoftware_commons_TestCommons_JUnit.__moduleBase;var H=F();if(o){var I=!!(o.location.protocol==Xb||o.location.protocol==Yb);o.__gwt_activeModules[S].canRedirect=I;function J(){var b=Zb;try{o.sessionStorage.setItem(b,b);o.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(I&&J()){var K=$b;var L=o.sessionStorage[K];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(L)){if(L&&(window.console&&console.log)){console.log(_b+L)}L=ab}if(L&&!o[K]){o[K]=true;o[K+ac]=C();var M=p.createElement(ib);M.src=L;var N=p.getElementsByTagName(ob)[V];N.insertBefore(M,N.firstElementChild||N.children[V]);return false}}}G();r(O,Wb);A(H);return true}
solutions_trsoftware_commons_TestCommons_JUnit.succeeded=solutions_trsoftware_commons_TestCommons_JUnit();